[project]
name = "htmx-django-intellisense"
version = "0.1.0"
description = "Developer tooling for HTMX Tags for Django"
readme = "README.md"
authors = [{ name = "Diego Gamboa", email = "difegam3@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "cyclopts>=4.22.5",
    "httpx2>=2.9.1",
    "packaging>=26.3",
    "pydantic>=2.13.4",
]

[project.scripts]
htmx-django-intellisense = "htmx_django_intellisense:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["prek>=0.4.12", "pyrefly>=1.2.0", "pytest>=9.1.1", "ruff>=0.16.1"]
docs = ["zensical>=0.0.53"]

[tool.uv]
default-groups = ["dev"]
exclude-newer = "P7D"
exclude-newer-package = { zensical = false }
